name: Deploy CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Connect to host and deploy system
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /Aoi-Ryo.com/
          git fetch
          git reset --hard origin/main
          cd ./infra/
          echo ${{secrets.PASSWORD}} | sudo -S docker compose up -d --build
